import {
  Activity,
  UserPlus,
  MessageCircle,
  Bot,
  Ambulance,
  Building2,
  Send,
  Bell,
  Radio,
  CheckCircle2,
  Siren,
  Shield,
  GitMerge,
} from "lucide-react";
import type { ActionType } from "./enums";

export const ACTION_TYPE_ICON: Record<ActionType, typeof Activity> = {
  STATUS_CHANGE: Activity,
  ROLE_ASSIGNED: UserPlus,
  MESSAGE: MessageCircle,
  AI_QUERY: Bot,
  TRANSPORT_DISPATCHED: Ambulance,
  HOSPITAL_RECOMMENDED: Building2,
  INSTITUTIONAL_NOTIFIED: Send,
  WELFARE_PROMPT: Bell,
  WELFARE_RESPONSE: Bell,
  PROXIMITY_ALERT: Radio,
  PROXIMITY_CONFIRMED: CheckCircle2,
  ESCALATION_STARTED: Siren,
  CONTACT_NOTIFIED: Send,
  MODERATOR_ACTION: Shield,
  INCIDENT_CREATED: Siren,
  INCIDENT_MERGED: GitMerge,
};

export const ACTION_TYPE_LABEL: Record<ActionType, string> = {
  STATUS_CHANGE: "Status changed",
  ROLE_ASSIGNED: "Coordination role assigned",
  MESSAGE: "Message posted",
  AI_QUERY: "AI Support Engine consulted",
  TRANSPORT_DISPATCHED: "Transport dispatched",
  HOSPITAL_RECOMMENDED: "Hospital recommended",
  INSTITUTIONAL_NOTIFIED: "Institutional responder notified",
  WELFARE_PROMPT: "Welfare check sent",
  WELFARE_RESPONSE: "Welfare check answered",
  PROXIMITY_ALERT: "Proximity alert",
  PROXIMITY_CONFIRMED: "On-scene presence confirmed",
  ESCALATION_STARTED: "Escalation started",
  CONTACT_NOTIFIED: "Emergency contact notified",
  MODERATOR_ACTION: "Moderator action",
  INCIDENT_CREATED: "Situation Room opened",
  INCIDENT_MERGED: "Merged with another report",
};
